### ISSUE TITLE
unable to install package on Jessie

### ISSUE THREAD

**Issue by Germling42** [ch1x0r/LinuxRespin#7]
I tried to install the package respin_1.1.0-1_all.deb but a few dependencies could not be resolved:

Entpacken von respin (1.1.0-1) ...
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von respin:
 respin hängt ab von casper; aber:
  Paket casper ist nicht installiert.
 respin hängt ab von ubiquity-frontend-debconf; aber:
  Paket ubiquity-frontend-debconf ist nicht installiert.
 respin hängt ab von xresprobe; aber:
  Paket xresprobe ist nicht installiert.

dpkg: Fehler beim Bearbeiten des Paketes respin (--install):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Trigger für desktop-file-utils (0.22-1) werden verarbeitet ...
Trigger für gnome-menus (3.13.3-6) werden verarbeitet ...
Trigger für mime-support (3.58) werden verarbeitet ...
Trigger für man-db (2.7.0.2-5) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 respin

**Comment by luskbo** [comment]
have you tried to run 'apt-get install -f' afterwards? Looks like you are missing dependencies. 
Running 'apt-get install -f' should resolve this.

**Comment by Peasantinus** [comment]
Yes, the command output I pasted here is from "apt-get -f install".

**Comment by Peasantinus** [comment]
No, I am again mistaken. The "apt-get -f install" part removes "respin".

**Comment by luskbo** [comment]
Have you updated your /etc/apt/sources.list ? 
It's possible that 'apt-get install -f' is removing respin because it can't find the dependencies. 

Try first to run 'apt-get update' and then try to reinstall respin dpkg.
It will still fail, but now try 'apt-get install -f'.
If it still fails, check your '/etc/apt/sources.list'

Make sure it contains links for 'main restricted universe multiverse'

Then 'apt-get update' and try to go the the process above again.

**Comment by Peasantinus** [comment]
No, this does not fix it. And as I said I am using Debian 8 Jessie.

**Comment by luskbo** [comment]
Okay, but regardless of Ubuntu repo address differences that I provided only as an example, have you checked to see if the required dependencies are even in the Debian repo urls that you are updating from? You output above is trying to resolve the following:


respin depends on casper ;
respin depends on ubiquity- frontend- debconf ;
respin depends on xresprobe ;

You are missing casper, ubiquity- frontend- debconf, and xresprobe.
You might just try and manually do an apt-get install or aptitude install on these to see if they are available in the Debian repos that you are using. If not, you may either need to update your repo.
Only a suggestion.

**Comment by ch1x0r** [comment]
Well, there shouldn't be ubiquity in the debian version! I'm going to work on this this weekend.

**Comment by ch1x0r** [comment]
I am having an issue installing on jessie too! I need to figure this one out - port, etc.

**Comment by xfally** [comment]
+1 for the same issue. Those dependencies are not exist in default debian repo.

**Comment by ch1x0r** [comment]
Okay I can understand it asking for Casper but the Debian version should not be asking for ubiquity at all...ever

**Comment by xfally** [comment]
I'm not sure, but found some doubts (maybe), 

I reviewed the control file in [respin_1.1.0-1_all.deb](https://github.com/ch1x0r/LinuxRespin/blob/master/respin_1.1.0-1_all.deb), which is different from [the one under debian dir](https://github.com/ch1x0r/LinuxRespin/blob/master/debian/debian-source/DEBIAN/control)

A mistake in the before one?

Also tried [debian/respin-deb_1.0.0-1_all.deb](https://github.com/ch1x0r/LinuxRespin/blob/master/debian/respin-deb_1.0.0-1_all.deb), but failed

```
$ sudo dpkg -i respin-deb_1.0.0-1_all.deb 
dpkg-deb: error: `respin-deb_1.0.0-1_all.deb' is not a debian format archive
dpkg: error processing archive respin-deb_1.0.0-1_all.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 respin-deb_1.0.0-1_all.deb
```

Should you fix it?

I reviewed https://packages.debian.org/jessie/live-tools, and think those pkgs are not necessary for Debian distribution. xresprobe is also moved to debports too.

**Comment by nesmrten** [comment]
I also cant make it work on jessie. Tried manny versions...

**Comment by ch1x0r** [comment]
Well, someone told me he could use it on Jessie. I need like 40 hours in a day instead of 24. Is there something we can do to arrange that? Now getting requests for other distros like Slitaz and CentOS.

**Comment by mas-dse-greina** [comment]
Is there a way to use apt-get on Ubuntu to install the package?

Thanks.
-Tony
